<?php
$students = array(
	"110101010" => array(
		"student_id" => 110101010,
		"name" => array("first_name" => "Ebru", "last_name" => "ÇİÇEKLİ"),
		"birth_year" => 1993,
		"registered_at" => 2011,
		"is_graduated" => false,
		"graduated_at" => null,
		"term" => 7,
		"department" => "Bilgisayar Mühendisliği",
		"lectures" => array(
			array("name" => "Web Programlama", "grade" => "FF"),
			array("name" => "Nesne Yönelimli Programla 1-2", "grade" => "BA"),
			array("name" => "Sanal Gerçeklik", "grade" => "CB"),
			array("name" => "Elektrik Devre Temelleri", "grade" => "BA"),
			),
		),
	"131210040" => array(
		"student_id" => 131210040,
		"name" => array("first_name" => "Şule", "last_name" => "TURP"),
		"birth_year" => 1995,
		"registered_at" => 2013,
		"is_graduated" => false,
		"graduated_at" => null,
		"term" => 7,
		"department" => "Bilgisayar Mühendisliği",
		"lectures" => array(
			array("name" => "Web Programlama", "grade" => "CC"),
			array("name" => "Nesne Yönelimli Programla 1-2", "grade" => "BA"),
			array("name" => "Olasılık ve İstatistik", "grade" => "BA"),
			array("name" => "Elektrik Devre Temelleri", "grade" => "FF"),
			),
		),
	"121044055" => array(
		"student_id" => 121044055,
		"name" => array("first_name" => "Merve", "last_name" => "SAKOĞLU"),
		"birth_year" => 1994,
		"registered_at" => 2012,
		"is_graduated" => false,
		"graduated_at" => null,
		"term" => 7,
		"department" => "Bilgisayar Mühendisliği",
		"lectures" => array(
			array("name" => "Veritabanı", "grade" => "CB"),
			array("name" => "Nesne Yönelimli Programla 1-2", "grade" => "FF"),
			array("name" => "Olasılık ve İstatistik", "grade" => "CB"),
			array("name" => "Elektrik Devre Temelleri", "grade" => "BA"),
			),
		),
	"48700691432" => array(
		"student_id" => 48700691432,
		"name" => array("first_name" => "Kemal Burak", "last_name" => "SÖZEN"),
		"birth_year" => 1991,
		"registered_at" => 2010,
		"is_graduated" => true,
		"graduated_at" => "2015",
		"term" => null,
		"department" => "Biyoloji",
		"lectures" => array(
			array("name" => "Adam Klonlama", "grade" => "AA"),
			array("name" => "Böcek Yenir mi?", "grade" => "BA"),
			array("name" => "Çiçekten Boya Yapımı", "grade" => "AA"),
			),
		),
	"130122038" => array(
		"student_id" => 130122038,
		"name" => array("first_name" => "Merve Rana", "last_name" => "SARI"),
		"birth_year" => 1995,
		"registered_at" => 2013,
		"is_graduated" => "hayır",
		"graduated_at" => null,
		"term" => 7,
		"department" => "BÖTE",
		"lectures" => array(
			array("name" => "İnternet Tabanlı Programlama", "grade" => "FF"),
			array("name" => "Ağ Dersi", "grade" => "CB"),
			array("name" => "İşletim Sistemleri", "grade" => "DD"),
			),
		),
	);

$bannedStudentIds = [110101010];